// Assign by hand same value to 3 variables in binary, octal and hexadecimal format.

const tenBinary = 0b1010;
const tenOctal = 0o12;
const tenHexadecimal = 0xA;

console.log(tenBinary, tenOctal, tenHexadecimal);

// Implement function `extractNumbers` which will leave only numbers in passed string.

function extractNumbers(text) {
  return parseFloat(text);
}

// Declare a variable with decimal value and convert to binary, octal and hexadecimal.

const variableDecimal = 123;

console.log(variableDecimal.toString(2));
console.log(variableDecimal.toString(8));
console.log(variableDecimal.toString(16));

// use `Math.random` to generate random value from `0` to `100`.

function random(min, max) {
  return (Math.round(min - 0.5 + Math.random() * (max - min + 1)));
}

// Make function which will take a array with numbers as a parameter and calculate average number and round to hundredths.

const array = [1, 3, 6, 6.5, 9, 12, 0, 123.123];

function calculation(array) {
  let count = 0;
  for (let i = 0; i < array.length; i++) {
    count += array[i];
  }
  console.log((count / array.length).toFixed(3));
}

// Generate array to pass to function above with values, and length generated by Math.random.

function newArray() {
  const arrayLength = Math.round(Math.random() * 100);
  let array = [];
  for (let i = 0; i < arrayLength; i++) {
    array[i] = Math.random();
  }
  return array;
}
